import { Roboto } from "next/font/google";
import "@/styles/globals.css";

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Notably App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <div flex justify-between items-center flex-col h-screen bg-gray-50>
          <div className="max-w-2xl w-full mx-auto">{children}</div>
        </div>
      </body>
    </html>
  );
}
